### ISSUE TITLE
有报错 

### ISSUE THREAD

**Issue by ms8922** [dzwvip/oracle#1]
oracle.go:106:34: invalid operation: limit > 0 (mismatched types *int and int)
oracle.go:108:36: cannot use limit (type *int) as type int in argument to strconv.Itoa

**Comment by ms8922** [comment]
go 1.16时报错

**Comment by dzwvip** [comment]
我刚才测试 Oracle 12c  用 limit offset 都可以的

**Comment by dzwvip** [comment]
和 go 版本没关系，估计是你用的 gorm 1.24 的 ，limit 改成指针 导致的，已经修复
