### ISSUE TITLE
不支持gorm 1.24 

### ISSUE THREAD

**Issue by rapinchen** [dzwvip/oracle#2]
gorm 1.24

oracle12c

..\..\..\pkg\mod\github.com\dzwvip\oracle@v1.2.4\oracle.go:106:36: cannot convert 0 (untyped int constant) to *int

..\..\..\pkg\mod\github.com\dzwvip\oracle@v1.2.4\oracle.go:108:37: cannot use limit (variable of type *int) as type int in argument to 
strconv.Itoa

**Comment by dzwvip** [comment]
update v1.2.5
