### ISSUE TITLE
Incorrect detection of 'not null' column modification upon app reopening

### ISSUE THREAD

**Issue by MuhmdHsn313** [dzwvip/oracle#4]
Related to issue #3 

The earlier problem has been resolved, however, a new problem arises upon closing and reopening the go app. The automatic migration detects that the column name in the language table needs to be changed to "not null", even though it is already "not null".

DB log:
```
[4.794ms] [rows:0] ALTER TABLE LANGUAGES MODIFY NAME varchar(50) NOT NULL
```

Go app log:
```
[FTAL] 2023/03/05 13:32 ORA-01442: column to be modified to NOT NULL is already NOT NULL
```

**Comment by dzwvip** [comment]
v1.2.8
